version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: Estefanini
      POSTGRES_USER: Estefanini
      POSTGRES_PASSWORD: EstefaniniPass
    ports:
      - "3254:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U PeriferiaSocial -d PeriferiaSocial"]
      interval: 5s
      timeout: 3s
      retries: 20
